
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luthfi RZ
 */
public class futama extends javax.swing.JFrame {

    /**
     * Creates new form futama
     */
    public futama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelnim = new javax.swing.JLabel();
        btntekan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        labelkelas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemograman Provis");
        setResizable(false);

        labelnim.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        labelnim.setForeground(new java.awt.Color(255, 0, 0));
        labelnim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnim.setText("NIM");
        labelnim.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btntekan.setText("Tekan Saya");
        btntekan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntekanMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelnama.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        labelnama.setForeground(new java.awt.Color(255, 0, 0));
        labelnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnama.setText("NAMA");

        labelkelas.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        labelkelas.setForeground(new java.awt.Color(255, 0, 0));
        labelkelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelkelas.setText("KELAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btntekan)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelnim, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelkelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(labelnim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelnama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelkelas)
                .addGap(14, 14, 14)
                .addComponent(btntekan)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntekanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntekanMouseClicked
        // TODO add your handling code here:
        labelnim.setText("NIM  : 10118312");
        labelnama.setText("NAMA : LUTHFI RIFQI ZULFIQAR");
        labelkelas.setText("KELAS : IF-8");
        JOptionPane.showMessageDialog(null,"Selamat anda berhasil menghubah label nama");
    }//GEN-LAST:event_btntekanMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntekan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelkelas;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelnim;
    // End of variables declaration//GEN-END:variables
}
